pipeline {
    agent {
        label "master"
    }

    stages {
        stage('Generate releases page') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'github-jenkins-api-key', variable: 'GITHUB_API_TOKEN'), string(credentialsId: 'slack-pr-monitor', variable: 'SLACK_URL')]) {
                      dir("release-versions") {
                        sh "python3 generate_release_file.py"
                      }
                    }
                    publishHTML (target: [
                      keepAll: true,
                      reportDir: "release-versions",
                      reportFiles: 'output.html',
                      reportName: "Release Version Report"
                    ])
                }
                
            }
        }
    }
}
