library("tdr-jenkinslib")
def repo = "tdr-scripts"

pipeline {
  agent {
    label "master"
  }
  parameters {
    choice(name: "STAGE", choices: ["intg", "staging", "prod"], description: "The stage you are creating the instance in")
    choice(name: "COMMAND", choices: ["apply", "destroy"], description: "Apply will create the instance")
    text(name: "PUBLIC_KEY", description: "Public key. This is not needed if you're not going to use ssh tunnelling")
    booleanParam(name: 'CONNECT_TO_BACKEND_CHECKS_EFS', defaultValue: false, description: 'Allow the bastion to connect to the backend checks EFS volume')
    booleanParam(name: 'CONNECT_TO_EXPORT_EFS', defaultValue: false, description: 'Allow the bastion to connect to the export EFS volume')
    booleanParam(name: 'CONNECT_TO_DATABASE', defaultValue: false, description: 'Allow the bastion to connect to the database')
  }
  stages {
    stage("Run git secrets") {
      steps {
        script {
          tdr.runGitSecrets(repo)
        }
      }
    }
    stage('Delete user if destroying bastion') {
      when {
        beforeAgent true
        expression { params.COMMAND == "destroy" }
      }
      agent {
        ecs {
          inheritFrom 'aws'
          taskrole "arn:aws:iam::${env.MANAGEMENT_ACCOUNT}:role/TDRJenkinsRunSsmRole${params.STAGE.capitalize()}"
        }
      }
      stages {
        stage('Run delete user script') {
          steps {
            script {
              def accountNumber = tdr.getAccountNumberFromStage(params.STAGE)
              //Role doesn't exist if database user was never created so we can skip deleting the user.
              sh "set +e"
              def status = sh(script: "aws sts assume-role --role-arn arn:aws:iam::${accountNumber}:role/TDRJenkinsRunDocumentRole${params.STAGE.capitalize()} --role-session-name check", returnStatus: true)
              sh "set -e"
              if(status == 0) {
                sh "python3 /run_ssm_command.py ${accountNumber} ${params.STAGE} bastion-ec2-instance-${params.STAGE} deleteuser"
              }
            }
          }
        }
      }
    }
    stage('Create user if connecting to database') {
      when {
        beforeAgent true
        expression { params.COMMAND == "apply" && params.CONNECT_TO_DATABASE == true }
      }
      agent {
        ecs {
          inheritFrom 'aws'
          taskrole "arn:aws:iam::${env.MANAGEMENT_ACCOUNT}:role/TDRJenkinsNodeLambdaRole${params.STAGE.capitalize()}"
        }
      }
      stages {
        stage('Run create user lambda') {
          steps {
            script {
              def accountNumber = tdr.getAccountNumberFromStage(params.STAGE)
              sh "python3 /invoke_lambda.py ${accountNumber} ${params.STAGE} tdr-create-bastion-user-${params.STAGE}"
            }
          }
        }
      }
    }
    stage('Run Terraform build') {
      agent {
        ecs {
          inheritFrom 'terraform'
          taskrole "arn:aws:iam::${env.MANAGEMENT_ACCOUNT}:role/TDRTerraformAssumeRole${params.STAGE.capitalize()}"
        }
      }
      environment {
        TF_VAR_tdr_account_number = tdr.getAccountNumberFromStage(params.STAGE)
        TF_VAR_public_key = "${params.PUBLIC_KEY}"
        //no-color option set for Terraform commands as Jenkins console unable to output the colour
        //making output difficult to read
        TF_CLI_ARGS="-no-color"
        TF_VAR_connect_to_database="${params.CONNECT_TO_DATABASE}"
        TF_VAR_connect_to_backend_checks_efs="${params.CONNECT_TO_BACKEND_CHECKS_EFS}"
        TF_VAR_connect_to_export_efs="${params.CONNECT_TO_EXPORT_EFS}"
      }
      stages {
        stage('Set up Terraform workspace') {
          steps {
            script {
              dir("terraform/bastion") {
                echo 'Initializing Terraform...'
                sh "git clone https://github.com/nationalarchives/tdr-terraform-modules.git"
                sh 'terraform init'
                //If Terraform workspace exists continue
                sh "terraform workspace new ${params.STAGE} || true"
                sh "terraform workspace select ${params.STAGE}"
              }
            }
          }
        }
        stage('Run terraform') {
          steps {
            script {
              dir("terraform/bastion") {
                sh "terraform ${COMMAND} -auto-approve"
                tdr.postToDaTdrSlackChannel(colour: "good", message: "Bastion instance has been ${params.COMMAND == 'apply' ? 'created' : 'destroyed'} for the ${params.STAGE} environment")
              }
            }
          }
        }
      }
    }
  }
  post {
    always {
      echo 'Deleting Jenkins workspace...'
      deleteDir()
    }
    failure {
      script {
        tdr.postToDaTdrSlackChannel(colour: "danger",
          message: "*Bastion script* :warning: The script to ${params.COMMAND} the bastion has failed"
        )
      }
    }
  }
}

