name: 'Terraform check'
on:
  push:
  pull_request:
permissions:
  id-token: write
  contents: write
jobs:
  check:
    uses: nationalarchives/tdr-github-actions/.github/workflows/terraform_check.yml@allow-other-working-directories
    with:
      working-directory: terraform
      use-workspace: false
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
